export const itSkills = [
  "Agile (Methodology)",
  "Amazon Web Services (AWS)",
  "Android Development",
  "Angular",
  "Apache Hadoop",
  "Apache Kafka",
  "Artificial Intelligence (AI)",
  "ASP.NET",
  "Atlassian Jira",
  "Automation Testing",
  "Azure DevOps",
  "Bash/Shell Scripting",
  "Big Data",
  "Blockchain",
  "Bootstrap",
  "Business Intelligence (BI)",
  "C",
  "C#",
  "C++",
  "Cisco Networking",
  "Cloud Computing",
  "Cloud Security",
  "CSS",
  "Cybersecurity",
  "Data Analysis",
  "Data Engineering",
  "Data Mining",
  "Data Science",
  "Data Visualization",
  "Database Management",
  "DevOps",
  "Django",
  "Docker",
  "Elasticsearch",
  "ETL (Extract, Transform, Load)",
  "Firebase",
  "Flask",
  "Git",
  "Go (Golang)",
  "Google Cloud Platform (GCP)",
  "GraphQL",
  "HTML",
  "Internet of Things (IoT)",
  "iOS Development",
  "IT Project Management",
  "ITIL (Information Technology Infrastructure Library)",
  "Java",
  "JavaScript",
  "Jenkins",
  "JSON",
  "Kubernetes",
  "Laravel",
  "Linux",
  "Machine Learning (ML)",
  "MATLAB",
  "Microsoft Access",
  "Microsoft Azure",
  "Microsoft Excel (Advanced)",
  "MongoDB",
  "MySQL",
  "Network Administration",
  "Node.js",
  "Numpy",
  "Oracle",
  "Oracle Database",
  "Pandas",
  "Penetration Testing",
  "Perl",
  "PHP",
  "Power BI",
  "PowerShell",
  "PostgreSQL",
  "Programming (General)",
  "Python",
  "R",
  "React",
  "React Native",
  "Redis",
  "RESTful APIs",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "Salesforce",
  "SAP",
  "SAS",
  "Scala",
  "Scrum (Framework)",
  "SEO (Search Engine Optimization)",
  "Software Development",
  "Software Testing",
  "Spring Boot",
  "SQL",
  "SQL Server",
  "Swift",
  "Terraform",
  "Troubleshooting",
  "TypeScript",
  "UI/UX Design",
  "Unity (Game Development)",
  "Virtualization (e.g., VMware, Hyper-V)",
  "Vue.js",
  "Web Development",
  "Web Security",
  "Windows Server",
  "WordPress",
  "XML",
  "Xamarin",
  "YAML",
  "Zend Framework",
  "Zookeeper"
];