export const financeRoles = {
  accountingRoles: [
    "Accounting Assistant",
    "Accounting Clerk",
    "Accounting Manager",
    "Accounts Payable Specialist",
    "Accounts Receivable Specialist",
    "Auditor",
    "Bookkeeper",
    "Chartered Accountant (CA)",
    "Cost Accountant",
    "Forensic Accountant",
    "General Ledger Accountant",
    "Management Accountant",
    "Payroll Administrator",
    "Payroll Manager",
    "Senior Accountant",
    "Staff Accountant",
    "Tax Accountant",
    "Tax Consultant"
  ],
  financialAnalysisRoles: [
    "Budget Analyst",
    "Business Analyst (Finance)",
    "Chief Financial Officer (CFO)",
    "Corporate Financial Analyst",
    "Financial Analyst",
    "Financial Consultant",
    "Financial Planning and Analysis (FP&A) Manager",
    "Investment Analyst",
    "Junior Financial Analyst",
    "Risk Analyst",
    "Senior Financial Analyst",
    "Treasury Analyst"
  ],
  auditingRoles: [
    "Audit Manager",
    "Compliance Analyst",
    "Compliance Manager",
    "External Auditor",
    "Forensic Auditor",
    "Internal Auditor",
    "Regulatory Compliance Officer"
  ],
  bankingRoles: [
    "Asset Manager",
    "Banking Relationship Manager",
    "Branch Manager",
    "Credit Analyst",
    "Financial Advisor",
    "Fund Manager",
    "Investment Banker",
    "Investment Manager",
    "Loan Officer",
    "Mortgage Advisor",
    "Private Equity Analyst",
    "Wealth Manager"
  ],
  taxAndTreasuryRoles: [
    "Corporate Tax Manager",
    "Indirect Tax Specialist",
    "International Tax Manager",
    "Tax Advisor",
    "Tax Manager",
    "Tax Specialist",
    "Treasury Accountant",
    "Treasury Manager"
  ],
  financeOperationsRoles: [
    "Accounts Payable Clerk",
    "Accounts Receivable Clerk",
    "Billing Specialist",
    "Chief Accounting Officer (CAO)",
    "Financial Controller",
    "Finance Manager",
    "Loan Processor",
    "Procurement Officer",
    "Revenue Analyst"
  ],
  specializedFinanceRoles: [
    "Cost Estimator",
    "Environmental Accountant",
    "Fund Accountant",
    "Grants Manager",
    "Government Accountant",
    "Healthcare Accountant",
    "Insurance Underwriter",
    "Project Accountant",
    "Real Estate Analyst",
    "Renewable Energy Financial Analyst"
  ]
};