export const itQualifications = [
  "None",
  "AWS Certified Cloud Practitioner",
  "AWS Certified Developer",
  "AWS Certified Solutions Architect",
  "AWS Certified SysOps Administrator",
  "Certified Cloud Security Professional (CCSP)",
  "Certified Data Management Professional (CDMP)",
  "Certified Ethical Hacker (CEH)",
  "Certified Information Security Manager (CISM)",
  "Certified Information Systems Auditor (CISA)",
  "Certified Information Systems Security Professional (CISSP)",
  "Certified Kubernetes Administrator (CKA)",
  "Certified ScrumMaster (CSM)",
  "Cisco Certified CyberOps Associate",
  "Cisco Certified DevNet Associate",
  "Cisco Certified Network Associate (CCNA)",
  "Cisco Certified Network Professional (CCNP)",
  "CompTIA A+",
  "CompTIA Advanced Security Practitioner (CASP)",
  "CompTIA Cloud+",
  "CompTIA Cybersecurity Analyst (CySA+)",
  "CompTIA Data+",
  "CompTIA Network+",
  "CompTIA PenTest+",
  "CompTIA Security+",
  "Google Associate Cloud Engineer",
  "Google Professional Cloud Architect",
  "Google Professional Data Engineer",
  "Information Technology Infrastructure Library (ITIL) Foundation",
  "ITIL Master Certification",
  "Microsoft Certified: Azure Administrator Associate",
  "Microsoft Certified: Azure AI Engineer Associate",
  "Microsoft Certified: Azure Data Scientist Associate",
  "Microsoft Certified: Azure Developer Associate",
  "Microsoft Certified: Azure Fundamentals",
  "Microsoft Certified: Azure Solutions Architect Expert",
  "Microsoft Certified: Power Platform Fundamentals (PL-900)",
  "Microsoft Certified: Security, Compliance, and Identity Fundamentals",
  "Oracle Certified Professional (OCP)",
  "PMI Agile Certified Practitioner (PMI-ACP)",
  "Project Management Professional (PMP)",
  "Red Hat Certified Engineer (RHCE)",
  "Red Hat Certified System Administrator (RHCSA)",
  "Scrum Master Certification (CSM)",
  "Six Sigma Certification (Green Belt, Black Belt)",
  "TOGAF (The Open Group Architecture Framework) Certification",
  "VMware Certified Professional (VCP)"
];